// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.3
// source: database/pubsub/auditprotobuf/audit.proto

package auditprotobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SimpleEvent2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Event    *SimpleEventContent2 `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	Metadata map[string]string    `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *SimpleEvent2) Reset() {
	*x = SimpleEvent2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_database_pubsub_auditprotobuf_audit_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SimpleEvent2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimpleEvent2) ProtoMessage() {}

func (x *SimpleEvent2) ProtoReflect() protoreflect.Message {
	mi := &file_database_pubsub_auditprotobuf_audit_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimpleEvent2.ProtoReflect.Descriptor instead.
func (*SimpleEvent2) Descriptor() ([]byte, []int) {
	return file_database_pubsub_auditprotobuf_audit_proto_rawDescGZIP(), []int{0}
}

func (x *SimpleEvent2) GetEvent() *SimpleEventContent2 {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *SimpleEvent2) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type SimpleEventContent2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EventName   string      `protobuf:"bytes,1,opt,name=eventName,proto3" json:"eventName,omitempty"`
	Timestamp   int64       `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	EventParams []*KeyPair2 `protobuf:"bytes,3,rep,name=eventParams,proto3" json:"eventParams,omitempty"`
}

func (x *SimpleEventContent2) Reset() {
	*x = SimpleEventContent2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_database_pubsub_auditprotobuf_audit_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SimpleEventContent2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimpleEventContent2) ProtoMessage() {}

func (x *SimpleEventContent2) ProtoReflect() protoreflect.Message {
	mi := &file_database_pubsub_auditprotobuf_audit_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimpleEventContent2.ProtoReflect.Descriptor instead.
func (*SimpleEventContent2) Descriptor() ([]byte, []int) {
	return file_database_pubsub_auditprotobuf_audit_proto_rawDescGZIP(), []int{1}
}

func (x *SimpleEventContent2) GetEventName() string {
	if x != nil {
		return x.EventName
	}
	return ""
}

func (x *SimpleEventContent2) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *SimpleEventContent2) GetEventParams() []*KeyPair2 {
	if x != nil {
		return x.EventParams
	}
	return nil
}

type KeyPair2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *KeyPair2) Reset() {
	*x = KeyPair2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_database_pubsub_auditprotobuf_audit_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeyPair2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyPair2) ProtoMessage() {}

func (x *KeyPair2) ProtoReflect() protoreflect.Message {
	mi := &file_database_pubsub_auditprotobuf_audit_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyPair2.ProtoReflect.Descriptor instead.
func (*KeyPair2) Descriptor() ([]byte, []int) {
	return file_database_pubsub_auditprotobuf_audit_proto_rawDescGZIP(), []int{2}
}

func (x *KeyPair2) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KeyPair2) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type SimpleEvent3 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Event    *SimpleEventContent3 `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	Metadata map[string]string    `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *SimpleEvent3) Reset() {
	*x = SimpleEvent3{}
	if protoimpl.UnsafeEnabled {
		mi := &file_database_pubsub_auditprotobuf_audit_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SimpleEvent3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimpleEvent3) ProtoMessage() {}

func (x *SimpleEvent3) ProtoReflect() protoreflect.Message {
	mi := &file_database_pubsub_auditprotobuf_audit_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimpleEvent3.ProtoReflect.Descriptor instead.
func (*SimpleEvent3) Descriptor() ([]byte, []int) {
	return file_database_pubsub_auditprotobuf_audit_proto_rawDescGZIP(), []int{3}
}

func (x *SimpleEvent3) GetEvent() *SimpleEventContent3 {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *SimpleEvent3) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type SimpleEventContent3 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EventName   string      `protobuf:"bytes,1,opt,name=eventName,proto3" json:"eventName,omitempty"`
	Timestamp   int64       `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	UserId      string      `protobuf:"bytes,3,opt,name=userId,proto3" json:"userId,omitempty"`
	Country     string      `protobuf:"bytes,4,opt,name=country,proto3" json:"country,omitempty"`
	EventParams []*KeyPair2 `protobuf:"bytes,5,rep,name=eventParams,proto3" json:"eventParams,omitempty"`
}

func (x *SimpleEventContent3) Reset() {
	*x = SimpleEventContent3{}
	if protoimpl.UnsafeEnabled {
		mi := &file_database_pubsub_auditprotobuf_audit_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SimpleEventContent3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimpleEventContent3) ProtoMessage() {}

func (x *SimpleEventContent3) ProtoReflect() protoreflect.Message {
	mi := &file_database_pubsub_auditprotobuf_audit_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimpleEventContent3.ProtoReflect.Descriptor instead.
func (*SimpleEventContent3) Descriptor() ([]byte, []int) {
	return file_database_pubsub_auditprotobuf_audit_proto_rawDescGZIP(), []int{4}
}

func (x *SimpleEventContent3) GetEventName() string {
	if x != nil {
		return x.EventName
	}
	return ""
}

func (x *SimpleEventContent3) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *SimpleEventContent3) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SimpleEventContent3) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *SimpleEventContent3) GetEventParams() []*KeyPair2 {
	if x != nil {
		return x.EventParams
	}
	return nil
}

var File_database_pubsub_auditprotobuf_audit_proto protoreflect.FileDescriptor

var file_database_pubsub_auditprotobuf_audit_proto_rawDesc = []byte{
	0x0a, 0x29, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x2f, 0x70, 0x75, 0x62, 0x73, 0x75,
	0x62, 0x2f, 0x61, 0x75, 0x64, 0x69, 0x74, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x61, 0x75, 0x64, 0x69, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xc8, 0x01, 0x0a, 0x0c, 0x53, 0x69, 0x6d,
	0x70, 0x6c, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x32, 0x12, 0x36, 0x0a, 0x05, 0x65, 0x76, 0x65,
	0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x32, 0x52, 0x05, 0x65, 0x76, 0x65, 0x6e,
	0x74, 0x12, 0x43, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x53, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x32, 0x2e, 0x4d,
	0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x08, 0x6d, 0x65,
	0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x3b, 0x0a, 0x0d, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a,
	0x02, 0x38, 0x01, 0x22, 0x8a, 0x01, 0x0a, 0x13, 0x53, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x32, 0x12, 0x1c, 0x0a, 0x09, 0x65,
	0x76, 0x65, 0x6e, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x65, 0x76, 0x65, 0x6e, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x37, 0x0a, 0x0b, 0x65, 0x76, 0x65, 0x6e, 0x74,
	0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4b, 0x65, 0x79, 0x50, 0x61,
	0x69, 0x72, 0x32, 0x52, 0x0b, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73,
	0x22, 0x32, 0x0a, 0x08, 0x4b, 0x65, 0x79, 0x50, 0x61, 0x69, 0x72, 0x32, 0x12, 0x10, 0x0a, 0x03,
	0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x22, 0xc8, 0x01, 0x0a, 0x0c, 0x53, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x33, 0x12, 0x36, 0x0a, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x53, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x43, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x33, 0x52, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x43, 0x0a,
	0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x27, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x69,
	0x6d, 0x70, 0x6c, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x33, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x64,
	0x61, 0x74, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0x1a, 0x3b, 0x0a, 0x0d, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22,
	0xbc, 0x01, 0x0a, 0x13, 0x53, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x43,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x33, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x76, 0x65, 0x6e, 0x74,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x65, 0x76, 0x65, 0x6e,
	0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x37, 0x0a, 0x0b, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x50, 0x61,
	0x72, 0x61, 0x6d, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4b, 0x65, 0x79, 0x50, 0x61, 0x69, 0x72,
	0x32, 0x52, 0x0b, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x42, 0x21,
	0x5a, 0x1f, 0x2e, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x2f, 0x70, 0x75, 0x62,
	0x73, 0x75, 0x62, 0x2f, 0x61, 0x75, 0x64, 0x69, 0x74, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_database_pubsub_auditprotobuf_audit_proto_rawDescOnce sync.Once
	file_database_pubsub_auditprotobuf_audit_proto_rawDescData = file_database_pubsub_auditprotobuf_audit_proto_rawDesc
)

func file_database_pubsub_auditprotobuf_audit_proto_rawDescGZIP() []byte {
	file_database_pubsub_auditprotobuf_audit_proto_rawDescOnce.Do(func() {
		file_database_pubsub_auditprotobuf_audit_proto_rawDescData = protoimpl.X.CompressGZIP(file_database_pubsub_auditprotobuf_audit_proto_rawDescData)
	})
	return file_database_pubsub_auditprotobuf_audit_proto_rawDescData
}

var file_database_pubsub_auditprotobuf_audit_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_database_pubsub_auditprotobuf_audit_proto_goTypes = []interface{}{
	(*SimpleEvent2)(nil),        // 0: commonproto.SimpleEvent2
	(*SimpleEventContent2)(nil), // 1: commonproto.SimpleEventContent2
	(*KeyPair2)(nil),            // 2: commonproto.KeyPair2
	(*SimpleEvent3)(nil),        // 3: commonproto.SimpleEvent3
	(*SimpleEventContent3)(nil), // 4: commonproto.SimpleEventContent3
	nil,                         // 5: commonproto.SimpleEvent2.MetadataEntry
	nil,                         // 6: commonproto.SimpleEvent3.MetadataEntry
}
var file_database_pubsub_auditprotobuf_audit_proto_depIdxs = []int32{
	1, // 0: commonproto.SimpleEvent2.event:type_name -> commonproto.SimpleEventContent2
	5, // 1: commonproto.SimpleEvent2.metadata:type_name -> commonproto.SimpleEvent2.MetadataEntry
	2, // 2: commonproto.SimpleEventContent2.eventParams:type_name -> commonproto.KeyPair2
	4, // 3: commonproto.SimpleEvent3.event:type_name -> commonproto.SimpleEventContent3
	6, // 4: commonproto.SimpleEvent3.metadata:type_name -> commonproto.SimpleEvent3.MetadataEntry
	2, // 5: commonproto.SimpleEventContent3.eventParams:type_name -> commonproto.KeyPair2
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_database_pubsub_auditprotobuf_audit_proto_init() }
func file_database_pubsub_auditprotobuf_audit_proto_init() {
	if File_database_pubsub_auditprotobuf_audit_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_database_pubsub_auditprotobuf_audit_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SimpleEvent2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_database_pubsub_auditprotobuf_audit_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SimpleEventContent2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_database_pubsub_auditprotobuf_audit_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KeyPair2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_database_pubsub_auditprotobuf_audit_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SimpleEvent3); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_database_pubsub_auditprotobuf_audit_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SimpleEventContent3); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_database_pubsub_auditprotobuf_audit_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_database_pubsub_auditprotobuf_audit_proto_goTypes,
		DependencyIndexes: file_database_pubsub_auditprotobuf_audit_proto_depIdxs,
		MessageInfos:      file_database_pubsub_auditprotobuf_audit_proto_msgTypes,
	}.Build()
	File_database_pubsub_auditprotobuf_audit_proto = out.File
	file_database_pubsub_auditprotobuf_audit_proto_rawDesc = nil
	file_database_pubsub_auditprotobuf_audit_proto_goTypes = nil
	file_database_pubsub_auditprotobuf_audit_proto_depIdxs = nil
}
