// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.18.1
// source: database/pubsub/auditprotobuf/audit.proto

package auditprotobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SimpleEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Event    *SimpleEventContent `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	Metadata map[string]string   `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *SimpleEvent) Reset() {
	*x = SimpleEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_database_pubsub_auditprotobuf_audit_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SimpleEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimpleEvent) ProtoMessage() {}

func (x *SimpleEvent) ProtoReflect() protoreflect.Message {
	mi := &file_database_pubsub_auditprotobuf_audit_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimpleEvent.ProtoReflect.Descriptor instead.
func (*SimpleEvent) Descriptor() ([]byte, []int) {
	return file_database_pubsub_auditprotobuf_audit_proto_rawDescGZIP(), []int{0}
}

func (x *SimpleEvent) GetEvent() *SimpleEventContent {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *SimpleEvent) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type SimpleEventContent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EventName   string     `protobuf:"bytes,1,opt,name=eventName,proto3" json:"eventName,omitempty"`
	Timestamp   int64      `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	EventParams []*KeyPair `protobuf:"bytes,3,rep,name=eventParams,proto3" json:"eventParams,omitempty"`
}

func (x *SimpleEventContent) Reset() {
	*x = SimpleEventContent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_database_pubsub_auditprotobuf_audit_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SimpleEventContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimpleEventContent) ProtoMessage() {}

func (x *SimpleEventContent) ProtoReflect() protoreflect.Message {
	mi := &file_database_pubsub_auditprotobuf_audit_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimpleEventContent.ProtoReflect.Descriptor instead.
func (*SimpleEventContent) Descriptor() ([]byte, []int) {
	return file_database_pubsub_auditprotobuf_audit_proto_rawDescGZIP(), []int{1}
}

func (x *SimpleEventContent) GetEventName() string {
	if x != nil {
		return x.EventName
	}
	return ""
}

func (x *SimpleEventContent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *SimpleEventContent) GetEventParams() []*KeyPair {
	if x != nil {
		return x.EventParams
	}
	return nil
}

type KeyPair struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *KeyPair) Reset() {
	*x = KeyPair{}
	if protoimpl.UnsafeEnabled {
		mi := &file_database_pubsub_auditprotobuf_audit_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeyPair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyPair) ProtoMessage() {}

func (x *KeyPair) ProtoReflect() protoreflect.Message {
	mi := &file_database_pubsub_auditprotobuf_audit_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyPair.ProtoReflect.Descriptor instead.
func (*KeyPair) Descriptor() ([]byte, []int) {
	return file_database_pubsub_auditprotobuf_audit_proto_rawDescGZIP(), []int{2}
}

func (x *KeyPair) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KeyPair) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_database_pubsub_auditprotobuf_audit_proto protoreflect.FileDescriptor

var file_database_pubsub_auditprotobuf_audit_proto_rawDesc = []byte{
	0x0a, 0x29, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x2f, 0x70, 0x75, 0x62, 0x73, 0x75,
	0x62, 0x2f, 0x61, 0x75, 0x64, 0x69, 0x74, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x61, 0x75, 0x64, 0x69, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xc5, 0x01, 0x0a, 0x0b, 0x53, 0x69, 0x6d,
	0x70, 0x6c, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x35, 0x0a, 0x05, 0x65, 0x76, 0x65, 0x6e,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x52, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x12,
	0x42, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x26, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x53, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x4d, 0x65, 0x74, 0x61,
	0x64, 0x61, 0x74, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64,
	0x61, 0x74, 0x61, 0x1a, 0x3b, 0x0a, 0x0d, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01,
	0x22, 0x88, 0x01, 0x0a, 0x12, 0x53, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x76, 0x65, 0x6e, 0x74,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x65, 0x76, 0x65, 0x6e,
	0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x12, 0x36, 0x0a, 0x0b, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x50, 0x61, 0x72, 0x61,
	0x6d, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4b, 0x65, 0x79, 0x50, 0x61, 0x69, 0x72, 0x52, 0x0b,
	0x65, 0x76, 0x65, 0x6e, 0x74, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x22, 0x31, 0x0a, 0x07, 0x4b,
	0x65, 0x79, 0x50, 0x61, 0x69, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x21,
	0x5a, 0x1f, 0x2e, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x2f, 0x70, 0x75, 0x62,
	0x73, 0x75, 0x62, 0x2f, 0x61, 0x75, 0x64, 0x69, 0x74, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_database_pubsub_auditprotobuf_audit_proto_rawDescOnce sync.Once
	file_database_pubsub_auditprotobuf_audit_proto_rawDescData = file_database_pubsub_auditprotobuf_audit_proto_rawDesc
)

func file_database_pubsub_auditprotobuf_audit_proto_rawDescGZIP() []byte {
	file_database_pubsub_auditprotobuf_audit_proto_rawDescOnce.Do(func() {
		file_database_pubsub_auditprotobuf_audit_proto_rawDescData = protoimpl.X.CompressGZIP(file_database_pubsub_auditprotobuf_audit_proto_rawDescData)
	})
	return file_database_pubsub_auditprotobuf_audit_proto_rawDescData
}

var file_database_pubsub_auditprotobuf_audit_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_database_pubsub_auditprotobuf_audit_proto_goTypes = []interface{}{
	(*SimpleEvent)(nil),        // 0: commonproto.SimpleEvent
	(*SimpleEventContent)(nil), // 1: commonproto.SimpleEventContent
	(*KeyPair)(nil),            // 2: commonproto.KeyPair
	nil,                        // 3: commonproto.SimpleEvent.MetadataEntry
}
var file_database_pubsub_auditprotobuf_audit_proto_depIdxs = []int32{
	1, // 0: commonproto.SimpleEvent.event:type_name -> commonproto.SimpleEventContent
	3, // 1: commonproto.SimpleEvent.metadata:type_name -> commonproto.SimpleEvent.MetadataEntry
	2, // 2: commonproto.SimpleEventContent.eventParams:type_name -> commonproto.KeyPair
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_database_pubsub_auditprotobuf_audit_proto_init() }
func file_database_pubsub_auditprotobuf_audit_proto_init() {
	if File_database_pubsub_auditprotobuf_audit_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_database_pubsub_auditprotobuf_audit_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SimpleEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_database_pubsub_auditprotobuf_audit_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SimpleEventContent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_database_pubsub_auditprotobuf_audit_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KeyPair); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_database_pubsub_auditprotobuf_audit_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_database_pubsub_auditprotobuf_audit_proto_goTypes,
		DependencyIndexes: file_database_pubsub_auditprotobuf_audit_proto_depIdxs,
		MessageInfos:      file_database_pubsub_auditprotobuf_audit_proto_msgTypes,
	}.Build()
	File_database_pubsub_auditprotobuf_audit_proto = out.File
	file_database_pubsub_auditprotobuf_audit_proto_rawDesc = nil
	file_database_pubsub_auditprotobuf_audit_proto_goTypes = nil
	file_database_pubsub_auditprotobuf_audit_proto_depIdxs = nil
}
